# E2 285 - Mtech ECE lab (2022)

Contributors: Aditya Gopalan, Abhigyan Dutta, Jaswanth Nischal Dokka

# Week 1: Python primer

Hi there! This is a beginning notebook which will introduce you to scientific programming with the Python language, its typical data structures and program statements. 

Python code is akin to English and is easily readable. This should make your job easy!

## How to use this notebook
* Prerequisites: Python 3, Jupyter notebook, the NumPy and PyTorch packages
* Think of each cell in this notebook as a "file" that holds code
* To execute the code in each cell of this notebook, press Shift+Enter
* Each cell, when executed, displays its intended output (or error messages) right below
* Try changing the code in each cell and running it. Play around and learn!
* Comments in Python begin with #
* If you get errors in code that you write, Google is often your best friend to search for answers!
* To look up help about a standard Python function, type ? followed immediately by the function name in a cell, e.g., ?print

In [1]:
# Hello world in Python

print("Hello world!") # print() is a built-in function in Python

Hello world!


In [2]:
# Hello world in Python, in some more detail
my_string = "Hello world, again!"
print(my_string)

Hello world, again!


## Basic variables and data types

In [3]:
# basic variables and data types in Python

n = 10 # integer 
x = 10.0 # floating point value
s = '10' # string

# note: you can use both single and double quotes equivalently for strings in Python

In [4]:
# check the types of the variables defined above
# type is a built-in function in Python

print(type(n))
print(type(x))
print(type(s))

<class 'int'>
<class 'float'>
<class 'str'>


## Basic data types

In [5]:
my_list = [1, 2, 3.651, -1.3, 10, "some string"] # a list, defined using square braces; each element or 'value' can be arbitrary
my_tuple = (1, 2, 3) # a tuple, defined using round braces; each element or 'value' can be arbitrary

my_dict = {'first_elem': 1.09, 'second_elem':2.21, 'third_elem':3.64} # a dictionary, defined using curly braces

# note: a dictionary allows for arbitrary indices or 'keys'
my_dict_2 = {'cat': 1.41, 'dog':456, 'rabbit':'blue'}

print(type(my_list))
print(type(my_tuple))
print(type(my_dict))
print(type(my_dict_2))

<class 'list'>
<class 'tuple'>
<class 'dict'>
<class 'dict'>


In [6]:
# a list is "mutable" (changeable) whereas a tuple is "immutable" (cannot be changed, equivalent to a "const" in C)

# so this would work ...
my_list[0] = 1000000000
print(my_list)

[1000000000, 2, 3.651, -1.3, 10, 'some string']


In [7]:
# ... but try running this and checking what happens 

my_tuple[0] = 1000000000

TypeError: 'tuple' object does not support item assignment

In [8]:
# accessing the contents of data structures

print(my_list[0]) # Note: Python follows C-style indexing: the first element has index 0, the second has index 1 and so on
print(my_list[2])
print(my_list[0:5:2]) # "slicing a list": The notation [x:y:s] means "extract elements with indices x, x+s, x+2s, x+3s, ... up to and NOT including y"

1000000000
3.651
[1000000000, 3.651, 10]


In [9]:
print(my_tuple[1])

2


In [10]:
print(my_dict['second_elem'])
print(my_dict_2['rabbit'])

2.21
blue


In [11]:
# Python list comprehension

# Python lists allow for very easy 1-line "English-style" manipulation called "list comprehension"

list1 = [3, 7, 5, -2, -6, 8]
list2 = [x+1 for x in list1] # in English: "the list of all x+1 where x is a member of list1"
print(list2)


[4, 8, 6, -1, -5, 9]


In [12]:
# conditional list comprehension

list3 = [x+1 for x in list1 if x > 0]
print(list3)

[4, 8, 6, 9]


## Program flow in Python: Conditionals, Loops

In [13]:
# conditional statements

a = 1.0
if a > 0:
    print('positive number')
else:
    print('non-positive number')
    
# Note: Proper and consistent indendation is important in Python! 

positive number


In [14]:
# multiple conditions to check

a = -5.0
if a > 0:
    print('positive number')
elif a > -1:
    print('negative number')
else:
    print('very negative number')


very negative number


In [15]:
# loops in Python

indices = [1, 2, 3, 4, 5, 6] # a list

for i in indices:
    print(i)


1
2
3
4
5
6


In [16]:
counter = 1

while(counter <= 6):
    print(counter)
    counter = counter + 1

1
2
3
4
5
6


In [17]:
counter = 1

# True and False are built-in Boolean constants defined in Python
while(True):
    if counter > 6:
        break
    print(counter)
    counter = counter + 1

1
2
3
4
5
6


## Functions

In [18]:
# definition of a function that squares its input

def f(x):
    return x*x

In [19]:
print(f(2.5))

6.25


In [20]:
# Will this work? 

print(f('2.5'))

# Why?

TypeError: can't multiply sequence by non-int of type 'str'

In [21]:
# Will this work? 

print(f(float('2.5')))

# Why?

6.25


## Classes and object oriented programming

Python allows for defining and using "classes" and "objects". Think of a class as defining a new "data type" structure but with an additional capability to compute. Instances of a class are called "objects".

Classes can inherit attributes and methods from other classes, just like in C++ or Java.

In [22]:
# example 1: definition of a class corresponding to a fruit

class Fruit():
    # class constructor function: defines what happens when you initialize the object
    def __init__(self, fruit_type): # note: "self" refers to the created object itself, and is required 
                            # when defining functions within classes
        self.name = fruit_type # each object in this Fruit class has an attribute called "name"
    
    def get_name(self): # A method that returns the name of the object. It is good practice to define  
                        # get_variable() and set_variable() functions to manipulate class attributes
                        # instead of directly manipulating them from outside
        return self.name
        

Note that each class _must_ define a *constructor* function, which has the special name \__init\__, which specifies how an object (instance of the class) is set up when first invoked. 

In [23]:
# a "child class" can be defined from a "parent class" -- this is called "inheritance"

class Apple(Fruit):
    def __init__(self, type_of_apple):
        super().__init__("apple") # call the parent class' constructor with fruit type "apple"
        self.apple_type = type_of_apple
    def get_apple_type(self):
        return self.apple_type
    
class Banana(Fruit):
    def __init__(self, rawness):
        super().__init__("banana") # call the parent class' constructor with fruit type "apple"
        self.maturity = rawness
        self.weight = 0.0
    def get_maturity(self):
        return self.maturity
    def get_weight(self):
        return self.weight
    def set_weight(self, wt):
        self.weight = wt

In [24]:
fruit1 = Fruit("mango") # instance of Fruit
print(fruit1.get_name())

mango


*Notes:* In the above code, Fruit("mango") creates an object (instance) of the Fruit class, and then calls its constructor with the argument "mango". The constructor assigns the string "mango" to the object's internal variable "name". 

The special keyword "self", used within an object, refers to the object itself. 

In [25]:
apple1 = Apple("red delicious")
print(apple1.get_name()) # the child class inherits the data and methods of the parent
print(apple1.get_apple_type())

apple
red delicious


In [26]:
banana1 = Banana("ripe")
print(banana1.get_name())
print(banana1.get_maturity())
print(banana1.get_weight())

banana1.set_weight(100)
print(f"after setting weight, banana1 has weight {banana1.get_weight()}")

banana
ripe
0.0
after setting weight, banana1 has weight 100


In [27]:
# example 2: A class that defines, say, a "smart" integer: an integer with the ability to square itself

class SmartInt():
    # class constructor function: defines what happens when you initialize the object
    def __init__(self, x): # note: "self" refers to the created object itself, and is required when defining functions within classes
        self.value = x
        self.original_value = x
    def get_value(self): # a class can contain functions defined like this; functions defined in a class are
                            # also called "methods"
        return self.value
    def square(self):
        self.value = self.value*self.value
    def reset(self):
        self.value = self.original_value
        
a = SmartInt(2)
print(a.get_value())

2


In [28]:
a.square() # note: the "self" argument is never explicitly passed
print(a.get_value())

a.square() 
print(a.get_value())

a.reset()
print(a.get_value())

4
16
2


In [29]:
# many instances of the same class can be created
b = SmartInt(3)
b.square()

print(b.get_value() + a.get_value())

11


In [30]:
# Lists are special classes built into Python. They have useful methods, e.g., sorting

some_list = [5, 2, 4, 3]
some_list.sort()
print(some_list)

[2, 3, 4, 5]


## Scientific programming with Python: NumPy and PyTorch

The core Python interpreter provides only basic mathematics facilities. NumPy and PyTorch are Python packages that permit greatly advanced mathematical operations such as linear algebra, randomness and sampling, tensors, neural networks and optimization. 


In [31]:
# import the NumPy package/library in our Python session, and calling it "np" for convenience

import numpy as np

In [32]:
# vectors and matrices in NumPy

# NumPy defines a basic class called an "ndarray" (think of it as a matrix from linear algebra)
# depending on a NumPy array's dimension, it becomes a vector (1D) or matrix (2D) or a general tensor (arbitrary dimensions)

# defining a vector 
v = np.array([3.5, 2.3, -1.45]) # the function np.array() converts a list into a NumPy ndarray

print(type(v))
v.shape # note the output: it has only one relevant dimension, so this is a vector

<class 'numpy.ndarray'>


(3,)

In [33]:
# a NumPy ndarray has a data type attribute called "dtype"

print(v.dtype)

float64


In [34]:
# the data type gets set automatically when an ndarray is constructed, depending on its contents

w = np.array([3, 2, -1])
print(w.dtype)

w1 = np.array([3.5, 2, -1])
print(w1.dtype) # one floating point number in an ndarray makes its overall type a float

int64
float64


In [35]:
# useful methods of an ndarray object
print(w.max()) # largest value
print(w.min()) # smalles value
print(w.argmax()) # index of largest value (smallest index if there are many)
print(w.argmin()) # index of smallest value (smallest index if there are many)
print(w.mean()) # average value

# Note: the same results can be achieved by calling the functions np.max, np.min, np.argmax, np.argmin and np.mean
# on the ndarray w; these are built-in functions that NumPy provides

3
-1
0
2
1.3333333333333333


In [36]:
# defining a matrix in NumPy
M = np.array([[5, 3, 8.7], [-9.2, 3.7, 8.75], [3.45, 2.19, 7]]) # a 3x3 matrix; each row defined explicitly

print(M.shape)

(3, 3)


In [37]:
# defining a tensor (i.e., a "higher order matrix") 

T = np.array([[[2, 3], [4, 5], [6, 7]], [[8, 9], [10, 11], [12, 13]]]) # a 2x3x2 tensor, or two 3x3 matrices 
                                                                        # "stacked" together 


print(T.shape)

(2, 3, 2)


In [38]:
# basic linear algebra with NumPy

# matrix vector product
print("M*v = ")
print(np.dot(M, v))

# matrix transposition
print("the transpose of M is")
print(M.T)

# matrix inversion
print("the inverse of M is ")
print(np.linalg.inv(M)) # np.linalg provides many useful linear algebra functions

M*v = 
[ 11.785  -36.3775   6.962 ]
the transpose of M is
[[ 5.   -9.2   3.45]
 [ 3.    3.7   2.19]
 [ 8.7   8.75  7.  ]]
the inverse of M is 
[[ 0.21659182 -0.06259061 -0.19095442]
 [ 3.04072408  0.16025383 -3.97950294]
 [-1.05806107 -0.01928833  1.48198631]]


### Random number generation in NumPy
np.random has several functions to return random samples. For instance:

In [39]:
# a randomly sampled 4x4 matrix with iid standard normal entries
# re-run this cell multiple times and observe the results

rand_mat = np.random.normal(size=(4,4))
print(rand_mat)

[[-0.25548269  2.27500923 -0.76466519  0.92467396]
 [-0.41952901  1.12252368 -1.79258446  0.4324592 ]
 [ 2.02031752 -0.47137847 -0.18003936  0.23650636]
 [-0.34560329 -1.14953245  0.69078245 -0.60086249]]


In [40]:
# a sample of a random variable uniformly distributed in the interval (0,1)
# re-run to observe multiple independent samples

sample = np.random.rand()
print(sample)

0.4776562514837509


In [41]:
# a bunch of 10 uniform random samples from within the interval (-4, 7)

samples = np.random.uniform(low=-4, high=7, size=(10))
print(samples)
print(type(samples))

[-3.73660934 -3.71065702  0.61824073 -3.18744285 -2.30324435  1.42740266
  1.34548049  2.72759174  6.08432081  5.29577183]
<class 'numpy.ndarray'>


In [42]:
# import the PyTorch package for neural network and ML-specific primitives

import torch

In [43]:
# PyTorch extends the ndarray data type of NumPy to a "tensor" class

# a tensor is like an ndarray but with more "information storage" capabilities when it comes to
# working with neural networks (more on this later)

# creating a 2x3 tensor
tr = torch.Tensor([[3, 5.24, 7], [9, 11, 13]])
print(tr)

tensor([[ 3.0000,  5.2400,  7.0000],
        [ 9.0000, 11.0000, 13.0000]])


In [44]:
# PyTorch is highly NumPy-friendly
# e.g., you can call any tensor's .numpy() method to get its primary data as an ndarray

print(tr.numpy())

[[ 3.    5.24  7.  ]
 [ 9.   11.   13.  ]]


## Exercises
In all the following exercises, you should use print() to demonstrate what is asked. You may also convey your thoughts by writing them as comments. 

1. Write code to output a _dictionary_ with the following contents: The keys ("indices") of the dictionary are the *strings* "1", "2", "3", ..., "20". The corresponding values are the *integers* $1, 2, 4, \ldots, 400$ (squares of the integer representations). Note: Ensure that the types of the keys and values are as specified!

In [ ]:
# you are free to chose your own variable names ..



2. Write a function that, given a list as input, outputs a list that contains the elements of the input list _in reverse order_. Call this function with a list of your choice and demonstrate that it works as intended.


In [ ]:
# you are free to chose your own variable or function names ..
# please dont use the built-in function for list reversal
 


3. Define a NumPy ndarray of shape (2, 3) and fill it up with your choice of numbers. Use the NumPy function flatten() to output a vector of length 6 that contains the same elements as this ndarray.

In [ ]:
# you are free to chose your own variable names ..


4. Define 2 NumPy vectors of length 5, with your choice of numbers. Use the Numpy functions hstack() and vstack() to output matrices of shape (2, 5) and (5, 2) containing these vectors as rows and columns, respectively. (Google for these functions in NumPy to understand how to use them.)

In [ ]:
# you are free to chose your own variable names ..


5. *Law of large numbers*. Generate 10 i.i.d. unbiased random coin flips (i.e., samples from a probability distribution taking value 0 or 1 with equal probability). Print the sample mean of the 10 coin flips. Repeat the procedure for 100, 1000 and 10000 coin flips, respectively. What do you conclude? 

In [ ]:
# Write your code here :

# you are free to define any functions if you want.



# Conclusion :(Please add the conclusion as comments below)
    

6. *Classes*. Define a class called Polynomial whose constructor takes a list of numbers as input. These numbers represent the coefficients of a polynomial starting from the zeroth order coefficient. Define a method called "eval" within this class that returns the polynomial evaluated at a given input value. Instantiate and demonstrate the eval method suitably. 

In [ ]:
# Define your class Here:





# Create an object of the type polynomial (you have defined above).
# You should demonstrate the "eval" function.



7. Continuing on the same theme, write a function "add" that takes as input two Polynomial objects and returns a Polynomial object that represents the sum function of the two polynomial function. Show that it works as expected. 

In [ ]:
# write your function definition here:




# Please demonstrate the working of the "add" function with an example.




8. Continuing further, define a subclass of Polynomial (i.e., a class that inherits from Polynomial) which, given a positive integer input $n$ at instantiation time, constructs the polynomial function corresponding to $f(x) = x^n + 1$. 

In [ ]:
# you can give your own class name 



#  Create an object of the class (that you have defined above).
#  Please demonstrate the working of the defined object.
